version: '2'
services:
    file_manager:
        image: eltonkola/docker_filemanager
        environment:
            PHP_ERROR_REPORTING : E_ALL & ~E_STRICT
            ADMIN : admin
            PASSWORD : password
        tty: true
        ports:
            - "85:80"
        volumes:
            - demo_volume:/workingdir
volumes:
  demo_volume:
    driver: local
